# pytest.ini
[pytest]
python_files = *_tests.py test_*.py  # Это мы добавили в предыдущем шаге
python_classes = Test*               # Устанавливает правила для имен классов
python_functions = test_*            # Устанавливает правила для имен функций
markers =
    registration: Запускает все тесты регистрации
    regression: для регрессионных тестов.
    authorization: Запускает тесты авторизации
    courses: для тестов, связанных с курсами.

