app_url=https://nikita-filonov.github.io/qa-automation-engineer-ui-course
headless=False
browsers=[<Browser.CHROMIUM: 'chromium'>]
test_user={'email': 'stage@gmail.com', 'username': 'username', 'password': 'password'}
test_data={'image_png_file': WindowsPath('testdata/files/image.png'), 'dondack_png_file': WindowsPath('testdata/files/dondack.png')}
videos_dir=videos
allure_results_dir=allure-results
tracing_dir=tracing
browser_state_file=browser-state.json
os_info=Windows, 11
python_version=3.14.5 (tags/v3.14.5:5607950, May 10 2026, 10:43:50) [MSC v.1944 64 bit (AMD64)]