name: UI tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:

      # 1. Получаем код
      - name: Check out repository
        uses: actions/checkout@v7.0.1

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.14'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      # 4. Запускаем тесты
      - name: Run Playwright tests
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses 2

      # 5. Получаем предыдущую историю Allure
      - name: Get Allure history
        uses: actions/checkout@v7.0.1
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 6. Генерируем Allure Report
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.15
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      # 7. Передаём отчет в следующую job
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report


  publish-report:

    # Ждём завершения run-tests
    needs: run-tests

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      # 8. Получаем Allure Report из первой job
      - name: Download Allure report
        uses: actions/download-artifact@v5
        with:
          name: allure-report
          path: allure-report

      # 9. Публикуем отчет
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report